[build]
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "22"

# Functions configuration
[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  function = "variorum-edge"
  path = "/api/variorum-edge"
