[build]
  command = ""
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/shakespeare"
  to = "/.netlify/functions/shakespeare"
  status = 200

[[edge_functions]]
  function = "variorum-edge"
  path = "/api/variorum-edge"
