[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# Functions are handled automatically by Netlify
# No need for explicit redirects for /.netlify/functions/*

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

[[edge_functions]]
  function = "variorum-edge"
  path = "/api/variorum-edge"
